---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    swck-injection: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        swck-agent-injected: "true"
    spec:
      containers:
        - name: nginx
          image: nginx:1.19